apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: change-me-root-password
  MYSQL_DATABASE: userapp
  MYSQL_USER: userapp
  MYSQL_PASSWORD: userapp_password
